### ISSUE TITLE
Missing keys error when loading pretrain model to train_sip.py

### ISSUE THREAD

**Issue by liuem607** [facebookresearch/CovidPrognosis#12]
Hi, I tried to fine tune train_sip.py by loading a pretrained model. I tried both download your provided models, or my own pretrained models, but it all gives me error at line 210: trainer.fit(model.model, datamodule=data_module)

The error says: "
Exception has occurred: RuntimeError
Error(s) in loading state_dict for SipModule:
	Missing key(s) in state_dict: "pos_weights", "model.features.conv0.weight", "model.features.norm0.weight", "model.features.norm0.bias", "model.features.norm0.running_mean", "model.features.norm0.running_var", "model.features.denseblock1.denselayer1.norm1.weight", "model.features.denseblock1.denselayer1.norm1.bias", "model.features.denseblock1.denselayer1.norm1.running_mean", "model.features.denseblock1.denselayer1.norm1.running_var", "model.features.denseblock1.denselayer1.conv1.weight", "model.features.denseblock1.denselayer1.norm2.weight", "model.features.denseblock1.denselayer1.norm2.bias", "model.features.denseblock1.denselayer1.norm2.running_mean", "model.features.denseblock1.denselayer1.norm2.running_var", "model.features.denseblock1.denselayer1.conv2.weight", "model.features.denseblock1.denselayer2.norm1.weight", "model.features.denseblock1.denselayer2.norm1.bias", "model.features.denseblock1.denselayer2.norm1.running_mean", "model.features.denseblock1.denselayer2.norm1.running_var", "model.features.denseblock1.denselayer2.conv1.weight", "model.features.denseblock1.denselayer2.norm2.weight", "model.features.denseblock1.denselayer2.norm2.bias", "model.features.denseblock1.denselayer2.norm2.running_mean", "model.features.denseblock1.denselayer2.norm2.running_var", "model.features.denseblock1.denselayer2.conv2.weight", "model.features.denseblock1.denselayer3.norm1.weight", "model.features.denseblock1.denselayer3.norm1.bias", 
........
"

But I can see that the model after declaration contains these keys. 

Any hint of why this is happening? Could it be an pytorch-lightning issue or what? 

Thanks in advance for help

**Comment by mmuckley** [comment]
Hello @liuem607, this does look like a PyTorch Lightning issue to me, mostly because it is looking for `pos_weights` in the dictionary. You need to pass in your model weights at this line:

https://github.com/facebookresearch/CovidPrognosis/blob/1c8625d36ef7ff1b19c457cd6b6e8543d4635c21/cp_examples/sip_finetune/train_sip.py#L188

which is then used for model construction, for example, here:

https://github.com/facebookresearch/CovidPrognosis/blob/1c8625d36ef7ff1b19c457cd6b6e8543d4635c21/cp_examples/sip_finetune/sip_finetune.py#L110

If you try to use a PyTorch Lightning feature like `resume_from_checkpoint`, then it expects the file to have the entire PyTorch Lightning dictionary, which includes more than just the model. To not bias too heavily towards PyTorch Lightning, the pretrained weights we have provided for this project only include the model weights, which is why we have to load this way.

Let me know if this helps with your question.

**Comment by liuem607** [comment]
Hi, thanks to your hint, I solve the problem by 

1) Provide path to pretrained-file in plmodules/XrayDataModule.py
2) Changed line  106 in sip_finetune/train_sip.py 
   "elif args.resume_from_checkpoint is None:"
    to
     "elif args.resume_from_checkpoint is not None:"

Best
